### ISSUE TITLE
Use guidance for Tileserver-GL

### ISSUE THREAD

**Issue by abenrob** [lukasmartinelli/osm-liberty#10]
Do there exist any examples showing how to use this style with Tileserver-GL?

**Comment by tristangio** [comment]
Same question here : I tried to use this style with tileserver-gl-light.
What i did : 
- npm install -g tileserver-gl-light
- copy osm-liberty.json to /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/styles
- copy all sprites from this repo to /usr/lib/node_modules/tileserver-gl-light/node_modules/tileserver-gl-styles/sprites

When i try osm-liberty I get this error in tileserver-gl-light : 
```
GET /styles/osm-liberty.json 500 38.043 ms - 1151
TypeError: Cannot read property 'replace' of undefined
    at fixUrl (/usr/lib/node_modules/tileserver-gl-light/src/serve_style.js:76:17)
    at /usr/lib/node_modules/tileserver-gl-light/src/serve_style.js:83:20
    at Array.forEach (native)
    at /usr/lib/node_modules/tileserver-gl-light/src/serve_style.js:81:37
    at Layer.handle [as handle_request] (/usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/lib/node_modules/tileserver-gl-light/node_modules/express/lib/router/index.js:330:12)
```
node --version = v6.9.3
I surely did something wrong or miss and important part, but I can't see what's missing

**Comment by lukasmartinelli** [comment]
@abenrob One problem you face for sure right now is that you don't have the vector tiles necessary for self hosting. The restyle now depends no longer on OSM2VectorTiles.

OpenMapTiles is the new source https://github.com/openmaptiles/openmaptiles which we will release beginning of next week - and then you can download the necessary vector tiles.

**Comment by abenrob** [comment]
Looking forward to it - thanks for the update!
